language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: EXK9enoU+w3S9Jp74AM7skdlVlIkkggnHF2acuZ0EQs6agE5sNLstE/P4Ys6/NGdI5XKQfFyQlUzstR1PkQCyb0w72Fw3Qbn+Z2BRg+RpNKn+KeYwTNjGqSxGy0v1ZdwkqG/pJRwjHvqUa2Vjz4ppxwHmeMgULeOsCThkcsoeAc=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Y2V+eKelVA/v2xKQAXubNAao2Mw9+cH4HqzF4fu9RDZI4joConNoKUoOFli0NZaXaIRg5rbp3+9uqBGhTym0ophqqIEaf6aVtNwk+n9haTh7JnQ+uWgVN8Q8Kxwzqv33RVHYsmJcSKLI3l9MZk8on0/GhWUJXyhNFjCGbf3aeSg=
sudo: false
